version: 2
jobs:
  build: &template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/workingless

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements_dev.txt
      - run:
          name: radon
          command: sh run_radon.sh
      - run:
          name: run tests
          command: sh run_tests.sh

  test-python-3.6:
    <<: *template
    docker:
      - image: circleci/python:3.6

  test-python-3.5:
    <<: *template
    docker:
      - image: circleci/python:3.5

  test-python-3.8:
    <<: *template
    docker:
      - image: circleci/python:3.8


workflows:
  version: 2
  test:
    jobs:
      - test-python-3.5
      - test-python-3.6
      - test-python-3.8
